import type { AppData } from "./types";

const now = new Date().toISOString();

export const SEED_DATA: AppData = {
  users: [
    {
      id: "user-admin",
      email: "admin@carinventory.my",
      phone: "+60100000001",
      name: "Admin",
      role: "admin",
      createdAt: now,
    },
    {
      id: "user-001",
      email: "sarah@example.com",
      phone: "+60123456701",
      name: "Sarah Chen",
      role: "seller",
      createdAt: now,
    },
    {
      id: "user-002",
      email: "james@example.com",
      phone: "+60123456702",
      name: "James Wilson",
      role: "seller",
      createdAt: now,
    },
    {
      id: "user-reseller",
      email: "reseller@carinventory.my",
      phone: "+60123456799",
      name: "Ahmad Reseller",
      role: "reseller",
      createdAt: now,
    },
    {
      id: "user-003",
      email: "maria@example.com",
      phone: "+60123456703",
      name: "Maria Garcia",
      role: "seller",
      createdAt: now,
    },
  ],
  vehicles: [
    {
      id: "veh-001",
      plateNumber: "BHK 3847",
      make: "Honda",
      model: "Accord",
      year: 2019,
      trim: "EX-L",
      mileage: 68000,
      color: "Silver",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "good",
      description:
        "Well maintained, single owner, all service records. No accidents.",
      status: "active",
      sellerId: "user-001",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-002",
      plateNumber: "VEA 4521",
      make: "Toyota",
      model: "Camry",
      year: 2020,
      trim: "SE",
      mileage: 56000,
      color: "White",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "excellent",
      description: "Like new condition. Garage kept. Extended warranty available.",
      status: "active",
      sellerId: "user-002",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-003",
      plateNumber: "WB 8892 K",
      make: "Tesla",
      model: "Model 3",
      year: 2022,
      trim: "Long Range",
      mileage: 29000,
      color: "Blue",
      transmission: "automatic",
      fuelType: "electric",
      conditionGrade: "excellent",
      description: "Full self-driving package. Premium interior. Supercharger included.",
      status: "active",
      sellerId: "user-003",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-004",
      plateNumber: "JHR 7710",
      make: "Ford",
      model: "F-150",
      year: 2019,
      trim: "XLT",
      mileage: 109000,
      color: "Black",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "good",
      description: "4x4 crew cab. Tow package. Bed liner included.",
      status: "active",
      sellerId: "user-001",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-005",
      plateNumber: "VJM 3305",
      make: "Toyota",
      model: "RAV4",
      year: 2021,
      trim: "XLE",
      mileage: 45000,
      color: "Gray",
      transmission: "automatic",
      fuelType: "hybrid",
      conditionGrade: "good",
      description: "Hybrid AWD. Great fuel economy. One owner.",
      status: "active",
      sellerId: "user-002",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-006",
      plateNumber: "WXY 9021",
      make: "Mazda",
      model: "CX-5",
      year: 2020,
      trim: "Touring",
      mileage: 72000,
      color: "Red",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "good",
      description: "Sporty crossover with premium Bose audio.",
      status: "active",
      sellerId: "user-003",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-007",
      plateNumber: "BPL 6614",
      make: "Chevrolet",
      model: "Silverado",
      year: 2020,
      trim: "LT",
      mileage: 88000,
      color: "White",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "fair",
      description: "Work truck with some bed scratches. Runs great.",
      status: "active",
      sellerId: "user-001",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "veh-008",
      plateNumber: "WA 5528 Q",
      make: "BMW",
      model: "3 Series",
      year: 2019,
      trim: "330i",
      mileage: 84000,
      color: "Black",
      transmission: "automatic",
      fuelType: "gas",
      conditionGrade: "good",
      description: "Sport package. Leather seats. Navigation.",
      status: "pending_review",
      sellerId: "user-002",
      createdAt: now,
      updatedAt: now,
    },
  ],
  photos: [
    { id: "ph-001", vehicleId: "veh-001", url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-002", vehicleId: "veh-002", url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-003", vehicleId: "veh-003", url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-004", vehicleId: "veh-004", url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-005", vehicleId: "veh-005", url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-006", vehicleId: "veh-006", url: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-007", vehicleId: "veh-007", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80", sortOrder: 0, isPrimary: true },
    { id: "ph-008", vehicleId: "veh-008", url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80", sortOrder: 0, isPrimary: true },
  ],
  valuations: [
    { id: "val-001", vehicleId: "veh-001", estimatedLow: 96614, estimatedMid: 105015, estimatedHigh: 113416, factors: { baseValue: 103000, mileageAdjustment: 2015, conditionMultiplier: 1.0, expectedMileage: 133000, actualMileage: 68000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-002", vehicleId: "veh-002", estimatedLow: 106019, estimatedMid: 115238, estimatedHigh: 124457, factors: { baseValue: 108000, mileageAdjustment: 1798, conditionMultiplier: 1.05, expectedMileage: 114000, actualMileage: 56000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-003", vehicleId: "veh-003", estimatedLow: 160936, estimatedMid: 174930, estimatedHigh: 188924, factors: { baseValue: 165000, mileageAdjustment: 1457, conditionMultiplier: 1.05, expectedMileage: 76000, actualMileage: 29000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-004", vehicleId: "veh-004", estimatedLow: 138685, estimatedMid: 150744, estimatedHigh: 162803, factors: { baseValue: 150000, mileageAdjustment: 744, conditionMultiplier: 1.0, expectedMileage: 133000, actualMileage: 109000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-005", vehicleId: "veh-005", estimatedLow: 116426, estimatedMid: 126550, estimatedHigh: 136674, factors: { baseValue: 125000, mileageAdjustment: 1550, conditionMultiplier: 1.0, expectedMileage: 95000, actualMileage: 45000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-006", vehicleId: "veh-006", estimatedLow: 105158, estimatedMid: 114302, estimatedHigh: 123446, factors: { baseValue: 113000, mileageAdjustment: 1302, conditionMultiplier: 1.0, expectedMileage: 114000, actualMileage: 72000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-007", vehicleId: "veh-007", estimatedLow: 133147, estimatedMid: 144725, estimatedHigh: 156303, factors: { baseValue: 160000, mileageAdjustment: 806, conditionMultiplier: 0.9, expectedMileage: 114000, actualMileage: 88000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
    { id: "val-008", vehicleId: "veh-008", estimatedLow: 126517, estimatedMid: 137519, estimatedHigh: 148521, factors: { baseValue: 136000, mileageAdjustment: 1519, conditionMultiplier: 1.0, expectedMileage: 133000, actualMileage: 84000 }, algorithmVersion: "v1.0-rule-based", createdAt: now },
  ],
  listings: [
    { id: "lst-001", vehicleId: "veh-001", sellerId: "user-001", ownerId: null, listingType: "owner", askingPrice: 108000, status: "active", viewCount: 42, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-002", vehicleId: "veh-002", sellerId: "user-002", ownerId: null, listingType: "owner", askingPrice: 118000, status: "active", viewCount: 67, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-003", vehicleId: "veh-003", sellerId: "user-reseller", ownerId: "user-003", listingType: "reseller", askingPrice: 178000, status: "active", viewCount: 128, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-004", vehicleId: "veh-004", sellerId: "user-001", ownerId: null, listingType: "owner", askingPrice: 149000, status: "active", viewCount: 31, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-005", vehicleId: "veh-005", sellerId: "user-002", ownerId: null, listingType: "owner", askingPrice: 128000, status: "active", viewCount: 55, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-006", vehicleId: "veh-006", sellerId: "user-003", ownerId: null, listingType: "owner", askingPrice: 116000, status: "active", viewCount: 23, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-007", vehicleId: "veh-007", sellerId: "user-001", ownerId: null, listingType: "owner", askingPrice: 142000, status: "active", viewCount: 18, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
    { id: "lst-008", vehicleId: "veh-008", sellerId: "user-002", ownerId: null, listingType: "owner", askingPrice: 139000, status: "pending_review", viewCount: 0, listedAt: now, expiresAt: null, createdAt: now, updatedAt: now },
  ],
  inquiries: [
    {
      id: "inq-001",
      listingId: "lst-001",
      buyerId: null,
      contactName: "Ahmad Rizal",
      contactEmail: "ahmad@example.com",
      message: "Is this still available? Can I view it this weekend?",
      status: "new",
      emailNotified: true,
      smsNotified: true,
      replyMessage: null,
      repliedAt: null,
      buyerEmailNotified: false,
      createdAt: now,
    },
    {
      id: "inq-002",
      listingId: "lst-003",
      buyerId: null,
      contactName: "Lee Wei Ming",
      contactEmail: "lee@example.com",
      message: "Interested in the Mazda for my client. Is negotiation possible?",
      status: "new",
      emailNotified: true,
      smsNotified: true,
      replyMessage: null,
      repliedAt: null,
      buyerEmailNotified: false,
      createdAt: now,
    },
  ],
};

export const MAKES = [
  "BMW",
  "Chevrolet",
  "Ford",
  "Honda",
  "Hyundai",
  "Mazda",
  "Nissan",
  "Subaru",
  "Tesla",
  "Toyota",
];
